import type { VocabularyListResponse, VocabularyWord } from "@/types";

/**
 * Static fixture standing in for GET /api/vocabulary.
 * Shape must stay in sync with docs/BACKEND_API_CONTRACT.md.
 */
const words: VocabularyWord[] = [
  {
    id: "voc_1",
    french: "Bonjour",
    english: "Hello / Good morning",
    gender: null,
    partOfSpeech: "expression",
    pronunciationIpa: "/bɔ̃.ʒuʁ/",
    audioUrl: null,
    exampleFr: "Bonjour, comment allez-vous ?",
    exampleEn: "Hello, how are you?",
    imageUrl: null,
    synonyms: ["Salut"],
    commonMistake: "Don't use \"Bonjour\" late in the evening — switch to \"Bonsoir\".",
    level: "A1",
    unitTitle: "Greetings",
    isFavorite: true,
    masteryStatus: "mastered",
    lastReviewedAt: "2026-06-28T09:00:00.000Z",
  },
  {
    id: "voc_2",
    french: "Le pain",
    english: "Bread",
    gender: "masculine",
    partOfSpeech: "noun",
    pronunciationIpa: "/lə pɛ̃/",
    audioUrl: null,
    exampleFr: "Je voudrais un peu de pain, s'il vous plaît.",
    exampleEn: "I would like some bread, please.",
    imageUrl: null,
    synonyms: [],
    commonMistake: "Learners often forget the nasal vowel in \"pain\" and pronounce it like \"pin\".",
    level: "A1",
    unitTitle: "Food & Dining",
    isFavorite: false,
    masteryStatus: "learning",
    lastReviewedAt: "2026-06-29T18:00:00.000Z",
  },
  {
    id: "voc_3",
    french: "La maison",
    english: "House",
    gender: "feminine",
    partOfSpeech: "noun",
    pronunciationIpa: "/la mɛ.zɔ̃/",
    audioUrl: null,
    exampleFr: "Notre maison est près du parc.",
    exampleEn: "Our house is near the park.",
    imageUrl: null,
    synonyms: ["Le logement", "La demeure"],
    commonMistake: null,
    level: "A1",
    unitTitle: "Home & Places",
    isFavorite: false,
    masteryStatus: "mastered",
    lastReviewedAt: "2026-06-20T09:00:00.000Z",
  },
  {
    id: "voc_4",
    french: "Manger",
    english: "To eat",
    gender: null,
    partOfSpeech: "verb",
    pronunciationIpa: "/mɑ̃.ʒe/",
    audioUrl: null,
    exampleFr: "Nous allons manger au restaurant ce soir.",
    exampleEn: "We are going to eat at the restaurant tonight.",
    imageUrl: null,
    synonyms: ["Se nourrir"],
    commonMistake: "The \"ge\" keeps its soft sound before \"a\" — conjugated as \"nous mangeons\", not \"mangons\".",
    level: "A1",
    unitTitle: "Food & Dining",
    isFavorite: true,
    masteryStatus: "learning",
    lastReviewedAt: "2026-06-30T12:00:00.000Z",
  },
  {
    id: "voc_5",
    french: "Merci beaucoup",
    english: "Thank you very much",
    gender: null,
    partOfSpeech: "expression",
    pronunciationIpa: "/mɛʁ.si bo.ku/",
    audioUrl: null,
    exampleFr: "Merci beaucoup pour votre aide.",
    exampleEn: "Thank you very much for your help.",
    imageUrl: null,
    synonyms: ["Merci mille fois"],
    commonMistake: null,
    level: "A1",
    unitTitle: "Greetings",
    isFavorite: false,
    masteryStatus: "mastered",
    lastReviewedAt: "2026-06-15T09:00:00.000Z",
  },
  {
    id: "voc_6",
    french: "L'addition",
    english: "The bill / check",
    gender: "feminine",
    partOfSpeech: "noun",
    pronunciationIpa: "/la.di.sjɔ̃/",
    audioUrl: null,
    exampleFr: "L'addition, s'il vous plaît.",
    exampleEn: "The bill, please.",
    imageUrl: null,
    synonyms: [],
    commonMistake: "Don't confuse with \"une addition\" in math — same word, context makes the meaning clear.",
    level: "A2",
    unitTitle: "Food & Dining",
    isFavorite: false,
    masteryStatus: "new",
    lastReviewedAt: null,
  },
  {
    id: "voc_7",
    french: "Quatre-vingts",
    english: "Eighty",
    gender: null,
    partOfSpeech: "adjective",
    pronunciationIpa: "/katʁ.vɛ̃/",
    audioUrl: null,
    exampleFr: "Il y a quatre-vingts personnes ici.",
    exampleEn: "There are eighty people here.",
    imageUrl: null,
    synonyms: [],
    commonMistake: "Numbers 70-99 use base-20 counting (\"four twenties\") — a common stumbling block for English speakers.",
    level: "A2",
    unitTitle: "Numbers",
    isFavorite: false,
    masteryStatus: "learning",
    lastReviewedAt: "2026-06-27T09:00:00.000Z",
  },
  {
    id: "voc_8",
    french: "La sœur",
    english: "Sister",
    gender: "feminine",
    partOfSpeech: "noun",
    pronunciationIpa: "/la sœʁ/",
    audioUrl: null,
    exampleFr: "Ma sœur habite à Lyon.",
    exampleEn: "My sister lives in Lyon.",
    imageUrl: null,
    synonyms: [],
    commonMistake: null,
    level: "A1",
    unitTitle: "Family",
    isFavorite: false,
    masteryStatus: "mastered",
    lastReviewedAt: "2026-06-10T09:00:00.000Z",
  },
  {
    id: "voc_9",
    french: "Le billet",
    english: "Ticket",
    gender: "masculine",
    partOfSpeech: "noun",
    pronunciationIpa: "/lə bi.jɛ/",
    audioUrl: null,
    exampleFr: "J'ai perdu mon billet de train.",
    exampleEn: "I lost my train ticket.",
    imageUrl: null,
    synonyms: ["Le ticket"],
    commonMistake: "\"Billet\" is for trains/planes/shows; \"ticket\" is more for buses/metro in everyday French.",
    level: "A2",
    unitTitle: "Travel",
    isFavorite: true,
    masteryStatus: "learning",
    lastReviewedAt: "2026-06-29T09:00:00.000Z",
  },
  {
    id: "voc_10",
    french: "Réserver",
    english: "To book / reserve",
    gender: null,
    partOfSpeech: "verb",
    pronunciationIpa: "/ʁe.zɛʁ.ve/",
    audioUrl: null,
    exampleFr: "Je voudrais réserver une table pour deux.",
    exampleEn: "I would like to book a table for two.",
    imageUrl: null,
    synonyms: [],
    commonMistake: null,
    level: "A2",
    unitTitle: "Travel",
    isFavorite: false,
    masteryStatus: "new",
    lastReviewedAt: null,
  },
  {
    id: "voc_11",
    french: "Difficile",
    english: "Difficult",
    gender: null,
    partOfSpeech: "adjective",
    pronunciationIpa: "/di.fi.sil/",
    audioUrl: null,
    exampleFr: "Cet examen était très difficile.",
    exampleEn: "This exam was very difficult.",
    imageUrl: null,
    synonyms: ["Compliqué", "Ardu"],
    commonMistake: null,
    level: "A2",
    unitTitle: "Adjectives",
    isFavorite: false,
    masteryStatus: "learning",
    lastReviewedAt: "2026-06-26T09:00:00.000Z",
  },
  {
    id: "voc_12",
    french: "Toujours",
    english: "Always",
    gender: null,
    partOfSpeech: "adverb",
    pronunciationIpa: "/tu.ʒuʁ/",
    audioUrl: null,
    exampleFr: "Elle arrive toujours à l'heure.",
    exampleEn: "She always arrives on time.",
    imageUrl: null,
    synonyms: [],
    commonMistake: "Not to be confused with \"toujours\" meaning \"still\" in some contexts (\"il est toujours là\").",
    level: "A2",
    unitTitle: "Adverbs",
    isFavorite: false,
    masteryStatus: "new",
    lastReviewedAt: null,
  },
];

const stats = {
  total: words.length,
  mastered: words.filter((w) => w.masteryStatus === "mastered").length,
  favorites: words.filter((w) => w.isFavorite).length,
  dueForReview: words.filter((w) => w.masteryStatus !== "mastered").length,
};

export const mockVocabularyData: VocabularyListResponse = { words, stats };

export const vocabularyUnits = Array.from(new Set(words.map((w) => w.unitTitle)));
